apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test1-ingress-resource
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: test1.yourhost.xyz
    http:
      paths:
      - path: /
        backend:
          serviceName: hello-app
          servicePort: 8080
